name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
homepage: https://github.com/leisim/logger_flutter

version: 0.7.1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  sensors: ^2.0.3
